services:
  # Flask API Service
  - type: web
    name: estateiq-api
    env: python
    buildCommand: pip install -r ml-model/api/requirements.txt
    startCommand: cd ml-model/api && gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: ml-model/api
    healthCheckPath: /health
    plan: free

  # React Frontend Service
  - type: web
    name: estateiq-frontend
    env: node
    buildCommand: |
      cd client
      npm ci
      npx tailwindcss init -p
      npm run build
    startCommand: cd client && npm run preview -- --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://estateiq-api.onrender.com
    healthCheckPath: /
    plan: free 