services:
  # Flask API Service
  - type: web
    name: estateiq-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      cd ml-model/api
      pip install -r requirements.txt
    startCommand: cd ml-model/api && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src/ml-model/api
      - key: FLASK_ENV
        value: production
      - key: GUNICORN_CMD_ARGS
        value: "--access-logfile=- --error-logfile=- --capture-output --enable-stdio-inheritance"
    healthCheckPath: /health
    healthCheckTimeout: 60
    plan: free

  # React Frontend Service
  - type: web
    name: estateiq-frontend
    env: node
    buildCommand: |
      cd client
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install
      npm install @emotion/react@11.11.0 @emotion/styled@11.11.0 @mui/material@5.14.0 @mui/icons-material@5.14.0 --save
      npm install vite@5.0.0 @vitejs/plugin-react@4.2.0 --save-dev
      npx tailwindcss init -p
      npm run build
    startCommand: cd client && npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://estateiq-api.onrender.com
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    plan: free 