name: Deploy EstateIQ

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-ml-api:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install ML API dependencies
        run: |
          cd ml-model/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy ML API to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-d027tlbe5dus73bgiom0/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY"

  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install frontend dependencies
        run: |
          cd client
          npm install
          
      - name: Build frontend
        run: |
          cd client
          npm run build
          
      - name: Deploy frontend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-d027tlbe5dus73bgion0/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" 