name: Deploy ML Model

on:
  push:
    paths:
      - 'ml-model/models/**'
      - 'ml-model/scripts/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd ml-model/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          FLASK_SERVICE_ID: ${{ secrets.RENDER_FLASK_SERVICE_ID }}
        run: |
          # Trigger deploy
          curl -X POST "https://api.render.com/v1/services/$FLASK_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" 